plank:
  job_url_template: 'job url template'
  report_template: 'report template'
  job_url_prefix: 'http://prometheus.io'
  allow_cancellations: true #kjsakjs
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 2h
    grace_period: 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190711-664ef040d"
      initupload: "gcr.io/k8s-prow/initupload:v20190711-664ef040d"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190711-664ef040d"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190711-664ef040d"

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 30m

prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit
